import{api}from'../api.js';import{navigateIfCurrent}from'../router.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export const projectCard=p=>`<article class="card"><a href="#/projects/${encodeURIComponent(p.id)}"><h2>${esc(p.name)}</h2></a>${p.vault_name?`<span class="badge">${esc(p.vault_name)}</span>`:''}<p>${Number(p.note_count)||0} notes · ${Number(p.session_count)||0} sessions · ${Number(p.due_count)||0} due</p></article>`;
export async function render(root,isCurrent=()=>true){
  const [home,vaults]=await Promise.all([api('/home'),api('/vaults')]);
  if(!isCurrent())return;
  root.innerHTML=`<div class="page-heading"><h2>Projects</h2><div><a class="button" href="#/review?scope=all">Review</a> <button id="new-project" type="button">New project</button></div></div><form id="project-form" hidden><label>Name<input name="name" maxlength="200" required></label><label>Vault (optional)<select name="vault_id"><option value="">No vault</option>${vaults.map(v=>`<option value="${esc(v.id)}">${esc(v.name)}</option>`).join('')}</select></label><p class="error" role="alert"></p><button>Create project</button></form><section class="cards">${home.projects.map(projectCard).join('')||'<p class="muted">Create your first project to begin collecting notes.</p>'}</section>`;
  const form=root.querySelector('#project-form');root.querySelector('#new-project').onclick=()=>{form.hidden=false;form.querySelector('input').focus()};form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button'),error=form.querySelector('.error'),data=new FormData(form);button.disabled=true;error.textContent='';try{const vaultID=data.get('vault_id');const project=await api('/projects',{method:'POST',body:{name:data.get('name'),vault_id:vaultID||null}});navigateIfCurrent(isCurrent,`#/projects/${encodeURIComponent(project.id)}`)}catch(reason){if(!isCurrent())return;error.textContent=`Could not create project: ${reason.message}`;button.disabled=false}};
}
