import{api}from'../api.js';import{navigateIfCurrent}from'../router.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export const treeRows=(projectID,entries)=>entries.map(entry=>entry.kind==='folder'?`<li class="folder">📁 ${esc(entry.path)}</li>`:`<li>📄 <a href="#/projects/${encodeURIComponent(projectID)}/notes/${encodeURIComponent(entry.note_id)}">${esc(entry.path)}</a></li>`).join('');
export const directPayload=(relative_path,body,review_mode)=>({relative_path,body,review_mode});
const publicationFingerprint=payload=>JSON.stringify([payload.relative_path,payload.body,payload.review_mode]);
export function nextPublicationKey(previous,payload,createKey=()=>crypto.randomUUID()){const fingerprint=publicationFingerprint(payload);return previous?.fingerprint===fingerprint?previous:{fingerprint,key:createKey()}}
export const bodyWithinByteLimit=(body,limit=1048576)=>new TextEncoder().encode(body).byteLength<=limit;
const routeSegment=value=>encodeURIComponent(value).replace(/'/g,'%27');
export const publicationDestination=(projectID,result)=>result?.note_id?`#/projects/${routeSegment(projectID)}/notes/${routeSegment(result.note_id)}`:null;
export function publicationResultState(projectID,publicationKey,result){const value=result||{};const destination=publicationDestination(projectID,value);return{publicationKey:destination?null:publicationKey,destination,message:`Publication ${value.status||'has no durable status'}${value.operation_id?` (operation ${value.operation_id})`:''}. No note was opened because no note ID was returned.`}}
export const noteViewer=note=>`<article class="note"><h3>${esc(note.relative_path)}</h3><pre>${esc(note.body)}</pre></article>`;
function errorText(reason,action){return `${action}: ${reason.status===409?'The vault contents conflict with stored metadata. ':''}${reason.message}`}
export async function renderNotes(root,projectID,noteID,isCurrent=()=>true){
  const encodedProject=encodeURIComponent(projectID);const tree=await api(`/projects/${encodedProject}/tree`);let viewer='';if(noteID)viewer=noteViewer(await api(`/notes/${encodeURIComponent(noteID)}`));
  if(!isCurrent())return;
  root.innerHTML=`<nav class="tabs"><a href="#/projects/${encodedProject}">Overview</a><a href="#/projects/${encodedProject}/notes">Notes</a></nav><h2>Source notes</h2><div class="notes-layout"><section><ul class="tree">${treeRows(projectID,tree)||'<li class="muted">No source notes yet.</li>'}</ul><details><summary>New folder</summary><form id="folder-form"><label>Relative path<input name="path" maxlength="512" required placeholder="guide/examples"></label><p class="error" role="alert"></p><button>Create folder</button></form></details><details><summary>New Markdown file</summary><form id="file-form"><label>Relative .md path<input name="path" maxlength="512" accept=".md" pattern=".*\.md$" required placeholder="guide/a.md"></label><label>Markdown body<textarea name="body" maxlength="1048576" required></textarea></label><label>Review mode<select name="review"><option value="none">None</option><option value="whole">Whole note</option><option value="bites">Bites</option></select></label><p class="status" role="status"></p><p class="error" role="alert"></p><button>Publish file</button></form></details></section>${viewer}</div>`;
  const folder=root.querySelector('#folder-form');folder.onsubmit=async event=>{event.preventDefault();const button=folder.querySelector('button'),error=folder.querySelector('.error');button.disabled=true;error.textContent='';try{await api(`/projects/${encodedProject}/folders`,{method:'POST',body:{path:new FormData(folder).get('path')}});await renderNotes(root,projectID,noteID,isCurrent)}catch(reason){if(!isCurrent())return;error.textContent=errorText(reason,'Could not create folder');button.disabled=false}};
  let publicationKey=null;const file=root.querySelector('#file-form');file.onsubmit=async event=>{event.preventDefault();const button=file.querySelector('button'),error=file.querySelector('.error'),status=file.querySelector('.status'),data=new FormData(file),payload=directPayload(data.get('path'),data.get('body'),data.get('review'));button.disabled=true;error.textContent='';status.textContent='';if(!bodyWithinByteLimit(payload.body)){error.textContent='Markdown body must be 1 MiB or less when encoded as UTF-8. Shorten the file and try again.';button.disabled=false;return}publicationKey=nextPublicationKey(publicationKey,payload);try{const result=await api(`/projects/${encodedProject}/direct-notes`,{method:'POST',headers:{'Idempotency-Key':publicationKey.key},body:payload});if(!isCurrent())return;const state=publicationResultState(projectID,publicationKey,result);if(state.destination){if(navigateIfCurrent(isCurrent,state.destination)){publicationKey=state.publicationKey}return}publicationKey=state.publicationKey;status.textContent=state.message;button.disabled=false}catch(reason){if(!isCurrent())return;error.textContent=errorText(reason,'Could not publish file');button.disabled=false}};
}
